//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Religion
    {
        public Religion()
        {
            this.StudentForms = new HashSet<StudentForm>();
        }
    
        public int Id { get; set; }
        public string ReligionName { get; set; }
    
        public virtual ICollection<StudentForm> StudentForms { get; set; }
    }
}
