//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public Nullable<int> Nation { get; set; }
        public Nullable<int> ReligionName { get; set; }
        public string DOB { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual Religion Religion { get; set; }
    }
}
